### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by LeKoArts** [angeloashmore/gatsby-node-helpers#1]
Hi!

I'm currently creating my first source plugin and realized that (as you mentioned) a lot of times the boilerplate is the same code. I want to create some more source plugins (I'm currently struggling with a Windows/Node "EPERM" issue) and would be interested in testing your helpers.

Do you have an example for using the helpers?

Best regards

**Comment by angeloashmore** [comment]
Hey, sorry for the late reply. The `README` includes some excerpts from `gatsby-source-shopify` on how it's used there.

https://github.com/angeloashmore/gatsby-source-shopify/tree/master/src

Look through `nodes.js` and `gatsby-node.js` to see it being used.

Let me know if you have any questions about it, though. 😃
