### ISSUE TITLE
Typescript declaration file

### ISSUE THREAD

**Issue by PMudra** [angeloashmore/gatsby-node-helpers#12]
First of all I want to thank you for your great work on this project.

Currently I am working on a gatsby source plugin and I have decided to use typescript for that. Unfortunately, I am not able to use this package right away because there is no declaration file.

Maybe it is an option for you to add declarations in the future?

**Comment by angeloashmore** [comment]
Hi @PMudra, my experience with TypeScript is very limited so I probably won't be able to provide sufficient type declarations. I'm definitely in favor of adding them if you (or anyone else) is able to submit a PR.

I'll leave this open until we can add a declaration file. Thanks!

**Comment by PMudra** [comment]
Hi @angeloashmore, I have start looking a little closer into the topic and even tried out a fairly new approach in a fork. I will submit a PR when I have everything setup. There will be some things to discuss, though.

**Comment by angeloashmore** [comment]
Handled in #18.
