### ISSUE TITLE
Get SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by seanmars** [angeloashmore/gatsby-node-helpers#19]
```
(function (exports, require, module, __filename, __dirname) { import{pascalCase as e,pascalCaseTransformMerge as t}from"pascal-case";import{camelC
  ase as r,camelCaseTransformMerge as n}from"camel-case";function a(){return(a=Object.assign||function(e){for(var t=1;t<arguments.length;t++){var r=
  arguments[t];for(var n in r)Object.prototype.hasOwnProperty.call(r,n)&&(e[n]=r[n])}return e}).apply(this,arguments)}const o=["id","internal","fiel
  ds","parent","children"],i=({typePrefix:i,fieldPrefix:c=i,createNodeId:l,createContentDigest:s})=>{const f=(...r)=>((...r)=>e(r.filter(e=>null!=e)
  .join(" "),{transform:t}))(i,...r),p=(...e)=>((...e)=>r(e.filter(e=>null!=e).join(" "),{transform:n}))(c,...e),d=(...e)=>l([i,...e].filter(e=>null
  !=e).join(" "));return{createTypeName:f,createFieldName:p,createNodeId:d,createNodeFactory:(...e)=>t=>{const r=a({},t,{id:d(...e,t.id),internal:{t
  ype:f(...e),contentDigest:s(t)}});for(const e of o)e in t&&(r[p(e)]=t[e]);return r}}};export{i as createNodeHelpers};
                                                                ^^^^^^
  SyntaxError: Cannot use import statement outside a module
```

**Comment by angeloashmore** [comment]
Hi @seanmars, could you provide more details on the error?

Where are you using the package? It is viewable on GitHub?

**Comment by angeloashmore** [comment]
This should be resolved now.

**Comment by benjamin-hull** [comment]
Hi @angeloashmore, I'm getting this error as well, though I'm not sure if it's the same cause. I'm fairly new to Gatsby. I'm using version 1.0.3.

In my (very early, basic) Gatsby site, I've run `npm install --save gatsby-node-helpers` and have the following in my gatsby-node.js file (and nothing else)

`import { createNodeHelpers } from 'gatsby-node-helpers'` 

 On running `npm run develop` I get: 
 
 ```
  Error: /Users/benjaminhull/sahmri/sahmri-site-template/gatsby-node.js:1
  (function (exports, require, module, __filename, __dirname) { import { createNodeHelpers } from 'gatsby-node-helpers'
                                                                ^^^^^^
  SyntaxError: Cannot use import statement outside a module

Is it me doing something wrong, or is this the same issue? Thanks!
```

**Comment by angeloashmore** [comment]
Hi @benjamin-hull,

That looks like a similar error, but it's happening for a different reason. In `gatsby-node.js`, your code must be written using Node.js's `require` rather than ES modules's `import`.

In your `gatsby-node.js` file, try replacing your import line with this:

```diff
- import { createNodeHelpers } from 'gatsby-node-helpers'
+ const { createNodeHelpers } = require('gatsby-node-helpers')
```

The README is a bit misleading in that it expects this library to be used as part of a greater compiled library that transforms those `import`s to `require` before usage. I'll open a new issue to update the documentation so it's easier for other to adopt.

Thanks for the report, and feel free to reply here if you're still experiencing that error.

**Comment by benjamin-hull** [comment]
Legend - thanks very much! I actually plan on moving my work to a plugin at some point - I'm just sketching stuff out for now.

Thanks again for the super fast response.
