### ISSUE TITLE
Possible to remove p-is-promise

### ISSUE THREAD

**Issue by angeloashmore** [angeloashmore/gatsby-node-helpers#3]
https://github.com/angeloashmore/gatsby-node-helpers/blob/604f1504bfa8c714b488f706edfe3154c4426fba/src/index.js#L120

Can this be replaced with `Promise.resolve(node).then({/* ... */})`?

**Comment by PMudra** [comment]
While looking into #12 I have noticed that this dependency is not up to date and also that there is no declaration file available for the used version. So removing it would be the simplest solution for that issue.

In my opinion you can go ahead and use `Promise.resolve` without any drawbacks. Do you have the time or do you want me to go ahead and create a PR?

**Comment by angeloashmore** [comment]
Middleware support will be removed in `v1.0.0` so this can be closed.
